### ISSUE TITLE
Expose some kind of metadata/manifest endpoints for each collection request

### ISSUE THREAD

**Issue by LukaszKundys** [NetrunnerDB/netrunnerdb-api-server#70]
It's not so important for requests like sides, types or even factions which are the small ones. While I'm starting an app and would like to check if currently cached database stored on device should be updated I need to download whole cards collection just to check `last_updated` field and compare it to existing ones date. In case of huge amounts of requests from different apps It would improve both backend performance as well as client side ones (data usage in this case).

**Comment by SimonThordal** [comment]
A candidate for this could be providing the client sending over an (ETag)[https://restfulapi.net/caching/] and the server responding  with a 304 Not Modified if there have been no changes to the data (as described here)[https://guides.rubyonrails.org/caching_with_rails.html#conditional-get-support].
This has the benefit of the client deciding whether it wants to use the cache by setting the `If-Not-Match` header and the server decides when to update the ETag and break the cache.

**Comment by plural** [comment]
The server is already sending etags over.   Additionally, all entries in the response contain an "udpated_at" attribute.

We're gonna be doing aggressive caching for the card pool and format data since that rarely changes and already have normal HTTP caching support.  If you are building something here and seeing something not working, holler, but this should Just Work now.
